// Generated by CoffeeScript 1.3.3
(function() {
  var PgnParser;

  PgnParser = (function() {
    var OPERATOR;

    OPERATOR = /(([NBRQK])?([a-h]?[1-8]?)?x?([a-h][1-8])(=[NBRQK])?([+#])?)\-([NBRQK])?([a-h]?[1-8]?)?x?([a-h][1-8])(=[NBRQK])?([+#])?/g;

    function PgnParser(file) {
      this.file = file;
      this.moves = [];
    }

    PgnParser.prototype.parse = function() {
      var moves,
        _this = this;
      moves = this.file.match(OPERATOR);
      return _.each(moves, function(move) {
        var from, to, _ref;
        _ref = move.split('-'), from = _ref[0], to = _ref[1];
        return _this.moves.push({
          from: from,
          to: to
        });
      });
    };

    return PgnParser;

  })();

  window.PgnParser = PgnParser;

}).call(this);
